<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="12876" started-at="2016-08-17T13:23:58Z" finished-at="2016-08-17T13:24:11Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="12876" started-at="2016-08-17T13:23:58Z" finished-at="2016-08-17T13:24:11Z">
      <class name="Test.NewTest_ZAP">
        <test-method status="PASS" signature="demarrageZap()[pri:0, instance:Test.NewTest_ZAP@47f37ef1]" name="demarrageZap" duration-ms="12" started-at="2016-08-17T14:23:58Z" finished-at="2016-08-17T14:23:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demarrageZap -->
        <test-method status="PASS" signature="lancementSelenium()[pri:2, instance:Test.NewTest_ZAP@47f37ef1]" name="lancementSelenium" duration-ms="11822" started-at="2016-08-17T14:23:58Z" finished-at="2016-08-17T14:24:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lancementSelenium -->
        <test-method status="FAIL" signature="generationReport()[pri:3, instance:Test.NewTest_ZAP@47f37ef1]" name="generationReport" duration-ms="1030" started-at="2016-08-17T14:24:10Z" finished-at="2016-08-17T14:24:11Z">
          <exception class="br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApiException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApiException: java.lang.NullPointerException
	at br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApi.callApiOther(ClientApi.java:324)
	at br.com.softplan.security.zap.zaproxy.clientapi.gen.Core.xmlreport(Core.java:547)
	at configZAP.Zap.GeneratingReport(Unknown Source)
	at Test.NewTest_ZAP.generationReport(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
Caused by: java.lang.NullPointerException
	at br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApi.callApiOther(ClientApi.java:319)
	... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApiException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generationReport -->
      </class> <!-- Test.NewTest_ZAP -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
